### ISSUE TITLE
Trouble with timerstart and the local active queue daemon exiting early

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#35] opened 2023-03-09 14:29 UTC
After https://github.com/shikokuchuo/mirai/commit/284104c677a8f96c64ce04889b98d51bd3d1cd50, I noticed odd things happening during and after experimenting with `timerstart`. If I start a client on my local Macbook with:

```r
daemons("ws://127.0.0.1:5000", nodes = 1)
```

And then call a server:

```r
Rscript -e 'mirai::server("ws://127.0.0.1:5000", walltime = 1000, timerstart = 1L)'
```

then `mirai`s have trouble evaluating even as the server stays online.

```{r}
# client
m <- mirai(1)
Sys.sleep(10)
m$data
#> 'unresolved' logi NA
```

The error persists if I set `timerstart` to `0L`, `1L`, or `2L`. Then, when I terminate all my R processes and then start a new `mirai::daemons("ws://127.0.0.1", nodes = 1)` client, the local active queue daemon exits within about a second and `daemons()$nodes` returns "'errorValue' int 5 | Timed out". after restarting my computer, the local active queue daemon does not start at all and I see the same "'errorValue' int 5 | Timed out".

**Comment by wlandau** [comment] 2023-03-09 14:39
A correction: `timerstart = 0L` seems to work as expected and run tasks successfully on my end. But with `timerstart = 1L`, simple tasks do not seem to complete even though `daemons()` shows the task assigned.

**Comment by shikokuchuo** [comment] 2023-03-09 15:03
Are you using the exact code above, because the daemons() calls do not include the port number.

**Comment by wlandau** [comment] 2023-03-09 15:36
No, sorry, I did supply the port number in my tests. Corrected in the OP and retried on my end to confirm.

**Comment by wlandau** [comment] 2023-03-09 15:38
Interestingly, in that test case, if I submit 2 tasks instead of 1, then only 1 task is listed as assigned.

```r
m1 <- mirai(1)
m2 <- mirai(2)
Sys.sleep(10)
m1$data
#> 'unresolved' logi NA
m2$data
#> 'unresolved' logi NA
daemons()
#> $connections
#>[1] 1
#>
#>$daemons
#>[1] 1
#>
#>$nodes
#>                    status_online status_busy tasks_assigned tasks_complete
#>ws://127.0.0.1:5000             1           1              1              0
```

**Comment by wlandau** [comment] 2023-03-09 15:42
In that test case above, I also observed that when I closed the server and client R processes, the active queue daemon process still showed running in `htop`.

**Comment by shikokuchuo** [comment] 2023-03-09 15:47
Ok thanks. Don't use 'timerstart' for now then. I'll take another look at it.

**Comment by shikokuchuo** [comment] 2023-03-09 19:34
I'm about to post a fix for this. Apologies - this new feature has been giving me problems since i implemented it yesterday morning. I was focused on fixing an even bigger problem caused by this that I didn't notice it wasn't entirely correct.

**Closed** 2023-03-09 19:35 UTC

**Comment by wlandau** [comment] 2023-03-09 20:58
No need to apologize, thank you for your fast responses. I can confirmed this issue is fixed on my end.
